### ISSUE TITLE
Support java.util.Map type for JMX Adapter

### ISSUE THREAD

**Issue by piotrwielgolaski-tomtom** [jolokia/jolokia#532] opened 2022-11-09 19:19 UTC
I have bean that return data in from of Map<String, Boolean>

Jolokia read it correctly, but fails on parsing 

I dig into internal and problem is with type conversion 
![image](https://user-images.githubusercontent.com/72873187/200920109-caf58c5f-bbdc-44bb-9906-c524d5ab7fa7.png)
it assume it is custom type with field empty 

so later in CompositeTypeConverter all fields are ignored

![image](https://user-images.githubusercontent.com/72873187/200920329-0429fed4-df70-4a1c-9065-373519ed68b9.png)

here is metadata from JMX console
![image](https://user-images.githubusercontent.com/72873187/200921515-fbaf05f4-95d6-454a-bf43-595b6493b006.png)

I wonder if we missing some converter ?

**Comment by skarsaune** [comment] 2022-12-12 06:32
@piotrwielgolaski-tomtom : Thanks for the report. I can try to reproduce this in a test. Normally the problem is the other way around ... that we get Map compatible JSON, but need to return CompositeData instead ....

**Comment by skarsaune** [comment] 2022-12-18 19:05
Was just able to reproduce in a test, will investigate a solution

**Comment by skarsaune** [comment] 2023-01-02 21:05
@piotrwielgolaski-tomtom : See above PR #538 , if you want you can pull it and test it in your usecase.

**Comment by piotrwielgolaski-tomtom** [comment] 2023-03-11 13:11
@skarsaune I put my finding in PR https://github.com/rhuss/jolokia/pull/538

**Comment by skarsaune** [comment] 2023-05-07 17:43
Thanks @piotrwielgolaski-tomtom that was reall helpful. Should be fixed in #538 now

**Closed** 2023-06-28 04:40 UTC
